rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
  - rbx-2

os:
  - linux
  - osx

dist: trusty

gemfile:
  - Gemfile

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
